apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk000-shared-workspace-pvc
  namespace: skala-tekton
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: efs-sc-shared

