apiVersion: v1
kind: Pod
metadata:
  name: sk199-kaniko-pod
  namespace: skala-practice
  labels:
    app: sk199
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/workspace/Dockerfile
        - --context=dir:///workspace
        - --destination=amdp-registry.skala-ai.com/skala25a/sk199-myfirst-api-server:1.0.0.python-kaniko-kube
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: workspace
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: harbor-registry-secret
        items:
          - key: .dockerconfigjson
            path: config.json   # /kaniko/.docker/config.json 로 마운트됨
    - name: workspace
      configMap:   # 또는 PVC, emptyDir, gitRepo 등 원하는 소스로 교체 가능
        name: kaniko-app-workspace
