apiVersion: v1
kind: Secret
metadata:
  name: sk000-git-repo
  namespace: skala-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: sk000-my-app
  type: git
  url: https://github.com/himang10/myfirst-api-server.git
  username: himang10
  project: skala
  password: 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
