apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sk000-ci-pipeline-run-d79fc409
  namespace: skala-tekton
spec:
  serviceAccountName: sk000-pipeline-sa
  pipelineRef:
    name: ci-pipeline
  params:
    - name: git-url
      value: https://github.com/himang10/myfirst-api-server.git
    - name: git-revision
      value: master
    - name: image-registry-url
      value: "amdp-registry.skala-ai.com"
    - name: image-registry-project
      value: "skala25a"
    - name: image-name
      value: sk000-myfirst-api-server
    - name: image-tag
      value: 1.0.0
    - name: dockerfile
      value: "Dockerfile"
    - name: context
      value: "."
    - name: k8s-deploy-path
      value: "k8s/deploy.yaml"
    - name: skip-tls-verify-registry
      value: "false"   # 필요하면 "true"
    - name: git-user-name
      value: himang10
    - name: git-user-email
      value: "skala@skala-ai.com"
  workspaces:
    - name: shared-workspace # 소스코드, 빌드산출물
      persistentVolumeClaim:
        claimName: sk000-shared-workspace-pvc  # shared-workspace PVC를 참조
    - name: maven-settings  # settings.xml
      persistentVolumeClaim:
        claimName: sk000-shared-workspace-pvc  # shared-workspace PVC를 참조
    - name: maven-local-repo  # m2 repository
      persistentVolumeClaim:
        claimName: sk000-shared-workspace-pvc  # shared-workspace PVC를 참조
  podTemplate:
    securityContext:
      fsGroup: 0
      runAsUser: 0
      runAsGroup: 0
  serviceAccountName: sk000-pipeline-sa
