apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sk000-springboot-listener
  namespace: skala-tekton
spec:
  serviceAccountName: sk000-pipeline-sa
  triggers:
    - name: sk000-springboot-trigger
      interceptors:
        - name: "github-filter"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref == 'refs/heads/master' || body.ref == 'refs/heads/main'"
          - name: "filter"
            value: "body.ref != 'refs/heads/gitops'"
      bindings:
        - ref: sk000-springboot-binding
      template:
        ref: sk000-springboot-trigger-template

